# Generated by Django 3.2.5 on 2021-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('SUBJECT', models.CharField(max_length=50)),
                ('MESSAGE', models.CharField(max_length=200)),
            ],
        ),
    ]
